# Generated by Django 3.0.3 on 2020-02-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appinput', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='dir_build_file',
            field=models.CharField(max_length=512, null=True, verbose_name='编译目录'),
        ),
    ]
