# Generated by Django 3.0.3 on 2020-02-18 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appinput', '0002_auto_20200217_1802'),
        ('envx', '0002_auto_20200217_2137'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deploy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploypool',
            name='app_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deploy_app_name', to='appinput.App', verbose_name='APP应用'),
        ),
        migrations.AddField(
            model_name='deploypool',
            name='branch_build',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deploypool',
            name='code_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deploypool',
            name='create_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='create_user', to=settings.AUTH_USER_MODEL, verbose_name='创建用户'),
        ),
        migrations.AddField(
            model_name='deploypool',
            name='deploy_no',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='deploypool',
            name='deploy_type',
            field=models.CharField(blank=True, choices=[('deployall', '发布所有'), ('deploypkg', '发布程序'), ('deploycfg', '发布配置'), ('rollback', '回滚')], max_length=255, null=True, verbose_name='发布程序或配置'),
        ),
        migrations.AddField(
            model_name='deploypool',
            name='env_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deploy_env_name', to='envx.Env', verbose_name='环境'),
        ),
        migrations.AddField(
            model_name='deploypool',
            name='is_build',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='软件是否编译成功'),
        ),
        migrations.AddField(
            model_name='deploypool',
            name='is_inc_tot',
            field=models.CharField(blank=True, choices=[('TOT', '全量部署'), ('INC', '增量部署')], max_length=255, null=True, verbose_name='全量或增量部署'),
        ),
        migrations.AddField(
            model_name='deploypool',
            name='jenkins_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deploypool',
            name='nginx_url',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='软件包服务器URL'),
        ),
        migrations.AlterField(
            model_name='deploypool',
            name='description',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='deploypool',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='发布单编号'),
        ),
    ]
