# Generated by Django 3.0.3 on 2020-02-17 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envx', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='env',
            options={},
        ),
        migrations.AlterModelTable(
            name='env',
            table='env',
        ),
    ]
